// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hexa_Hub.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240908162639_IntialCheck1")]
    partial class IntialCheck1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder ModelBuilder)
        {
#pragma warning disable 612, 618
            ModelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(ModelBuilder);

            ModelBuilder.Entity("Asset", b =>
                {
                    b.Property<int>("assetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("assetId"));

                    b.Property<string>("assetDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("assetImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("assetName")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<int>("assetStatus")
                        .HasColumnType("int");

                    b.Property<int>("categoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("expiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<DateTime>("manufacturingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("serialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("subCategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("assetId");

                    b.HasIndex("categoryId");

                    b.HasIndex("subCategoryId");

                    b.ToTable("Assets");
                });

            ModelBuilder.Entity("AssetAllocation", b =>
                {
                    b.Property<int>("AllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AllocationId"));

                    b.Property<DateTime>("AllocatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("assetId")
                        .HasColumnType("int");

                    b.Property<int>("AssetReqId")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("AllocationId");

                    b.HasIndex("assetId");

                    b.HasIndex("AssetReqId")
                        .IsUnique();

                    b.HasIndex("userId");

                    b.ToTable("AssetAllocations");
                });

            ModelBuilder.Entity("AssetRequest", b =>
                {
                    b.Property<int>("AssetReqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssetReqId"));

                    b.Property<int>("assetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssetReqDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssetReqReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("categoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Request_Status")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("AssetReqId");

                    b.HasIndex("assetId");

                    b.HasIndex("userId");

                    b.ToTable("AssetRequests");
                });

            ModelBuilder.Entity("Audit", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditId"));

                    b.Property<int>("assetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AuditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuditMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Audit_Status")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("AuditId");

                    b.HasIndex("assetId");

                    b.HasIndex("userId");

                    b.ToTable("Audits");
                });

            ModelBuilder.Entity("Category", b =>
                {
                    b.Property<int>("categoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("categoryId"));

                    b.Property<string>("categoryName")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.HasKey("categoryId");

                    b.ToTable("Categories");
                });

            ModelBuilder.Entity("MaintenanceLog", b =>
                {
                    b.Property<int>("MaintenanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaintenanceId"));

                    b.Property<int>("assetId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Maintenance_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Maintenance_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("MaintenanceId");

                    b.HasIndex("assetId");

                    b.HasIndex("userId");

                    b.ToTable("MaintenanceLogs");
                });

            ModelBuilder.Entity("ReturnRequest", b =>
                {
                    b.Property<int>("ReturnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReturnId"));

                    b.Property<int>("assetId")
                        .HasColumnType("int");

                    b.Property<int>("categoryId")
                        .HasColumnType("int");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReturnStatus")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("ReturnId");

                    b.HasIndex("assetId");

                    b.HasIndex("userId");

                    b.ToTable("ReturnRequests");
                });

            ModelBuilder.Entity("ServiceRequest", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<int>("assetId")
                        .HasColumnType("int");

                    b.Property<int>("Issue_Type")
                        .HasColumnType("int");

                    b.Property<string>("ServiceDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceReqStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("ServiceRequestDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("ServiceId");

                    b.HasIndex("assetId");

                    b.HasIndex("userId");

                    b.ToTable("ServiceRequests");
                });

            ModelBuilder.Entity("SubCategory", b =>
                {
                    b.Property<int>("subCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("subCategoryId"));

                    b.Property<int>("categoryId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("subCategoryName")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.HasKey("subCategoryId");

                    b.HasIndex("categoryId");

                    b.ToTable("SubCategories");
                });

            ModelBuilder.Entity("User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("branch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dept")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<int>("User_Type")
                        .HasColumnType("int");

                    b.HasKey("userId");

                    b.ToTable("Users");
                });

            ModelBuilder.Entity("UserProfile", b =>
                {
                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dept")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ProfileImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("userMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.HasKey("userId");

                    b.ToTable("UserProfiles");
                });

            ModelBuilder.Entity("Asset", b =>
                {
                    b.HasOne("Category", "Category")
                        .WithMany("Assets")
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SubCategory", "SubCategories")
                        .WithMany("Assets")
                        .HasForeignKey("subCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("SubCategories");
                });

            ModelBuilder.Entity("AssetAllocation", b =>
                {
                    b.HasOne("Asset", "Asset")
                        .WithMany("AssetAllocations")
                        .HasForeignKey("assetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AssetRequest", "AssetRequests")
                        .WithOne("AssetAlocation")
                        .HasForeignKey("AssetAllocation", "AssetReqId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany("AssetAllocations")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("AssetRequests");

                    b.Navigation("User");
                });

            ModelBuilder.Entity("AssetRequest", b =>
                {
                    b.HasOne("Asset", "Asset")
                        .WithMany("AssetRequests")
                        .HasForeignKey("assetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany("AssetRequests")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("User");
                });

            ModelBuilder.Entity("Audit", b =>
                {
                    b.HasOne("Asset", "Asset")
                        .WithMany("Audits")
                        .HasForeignKey("assetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany("Audits")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("User");
                });

            ModelBuilder.Entity("MaintenanceLog", b =>
                {
                    b.HasOne("Asset", "Asset")
                        .WithMany("MaintenanceLogs")
                        .HasForeignKey("assetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany("MaintenanceLogs")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("User");
                });

            ModelBuilder.Entity("ReturnRequest", b =>
                {
                    b.HasOne("Asset", "Asset")
                        .WithMany("ReturnRequests")
                        .HasForeignKey("assetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany("ReturnRequests")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("User");
                });

            ModelBuilder.Entity("ServiceRequest", b =>
                {
                    b.HasOne("Asset", "Asset")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("assetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("User");
                });

            ModelBuilder.Entity("SubCategory", b =>
                {
                    b.HasOne("Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            ModelBuilder.Entity("UserProfile", b =>
                {
                    b.HasOne("User", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("UserProfile", "userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            ModelBuilder.Entity("Asset", b =>
                {
                    b.Navigation("AssetAllocations");

                    b.Navigation("AssetRequests");

                    b.Navigation("Audits");

                    b.Navigation("MaintenanceLogs");

                    b.Navigation("ReturnRequests");

                    b.Navigation("ServiceRequests");
                });

            ModelBuilder.Entity("AssetRequest", b =>
                {
                    b.Navigation("AssetAlocation");
                });

            ModelBuilder.Entity("Category", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("SubCategories");
                });

            ModelBuilder.Entity("SubCategory", b =>
                {
                    b.Navigation("Assets");
                });

            ModelBuilder.Entity("User", b =>
                {
                    b.Navigation("AssetAllocations");

                    b.Navigation("AssetRequests");

                    b.Navigation("Audits");

                    b.Navigation("MaintenanceLogs");

                    b.Navigation("ReturnRequests");

                    b.Navigation("ServiceRequests");

                    b.Navigation("UserProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
